on:
  push:
    branches:
      - master

jobs:
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    name: Docker Build, Tag, Push

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build, Tag, Push
      uses: mattdavis0351/actions/docker-gpr@v1.3.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: hartshuttlebot
